In [1]:
using Flows
using ToySystems
using ToySystems.NineModeSystemEq
using Optim
include("9msctrl.jl")
include("Initial condition variation.jl")
include("Perturbation time.jl")
include("Contour Plots.jl")
include("Magnitude Rand.jl")
include("Objective function Monitor.jl")
import LinearAlgebra: norm
using PyPlot; pygui(true)
using PyCall
np = pyimport("numpy")
sc = pyimport("scipy")
plt = pyimport("matplotlib.pyplot");

┌ Info: Recompiling stale cache file C:\Users\Kaijie\.julia\compiled\v1.2\ToySystems\chsON.ji for ToySystems [53c88820-6eff-5a8c-9a74-badd815e7be1]
└ @ Base loading.jl:1240
┌ Warning: Package ToySystems does not have Flows in its dependencies:
│ - If you have ToySystems checked out for development and have
│   added Flows as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with ToySystems
└ Loading Flows into ToySystems from project dependency, future warnings for ToySystems are suppressed.


In [2]:
Re_range = 50:10:500
alpha_range = 0.01:0.01:0.2
xx,yy = np.meshgrid(Re_range,alpha_range)
mesh = []
for i in 1:length(xx)
    push!(mesh, [xx[i],yy[i]])
end

Realphapush = []

for i in 1:length(xx)
    push!(Realphapush, [xx[i],yy[i]])
end

for i in 1:length(Realphapush)
    Re,α = Realphapush[i]
end

In [3]:
##Parameters
timestep = 0.5

dadt = zeros(9)
q    = zeros(9)
dqdt = zeros(9)
store = RAMStorage(zeros(9))
B = [0,0,0,0,1,0,0,0,0]

9-element Array{Int64,1}:
 0
 0
 0
 0
 1
 0
 0
 0
 0

Inipointnum (generic function with 3 methods)

In [23]:
d = Inipointnum(10, 0.1, false)

10-element Array{Any,1}:
 [0.03011915571194885, 0.01742622030540807, 0.017532821341338777, 0.034286382937341646, 0.01191290135908247, 0.02591103681964841, 0.05715629147165581, 0.036533359250395324, 0.04349000327870418]      
 [0.01151700470985547, 0.019825733676990292, 0.007403197702701536, 0.012310751636380391, 0.0465391755708242, 0.039051862463780174, 0.007304890075459436, 0.0633733565478036, 0.03882589832512192]      
 [0.02962502374791977, 0.04915539569443436, 0.008347900983722205, 0.0539402123321051, 0.024643165990928695, 0.04706886605007145, 0.021440197959333246, 0.011768760000016735, 0.01749061185387006]      
 [0.05555176690340026, 0.016901035400253638, 0.03167048094402416, 0.05094913623467087, 0.005514229845549092, 0.00040067906881615387, 0.052690799831734414, 0.014587415269403723, 0.0031371968967756516]
 [0.02549123073132747, 0.019235171062515755, 0.0194569514369063, 0.005680871693546889, 0.08687992683378731, 0.017484846781281437, 0.025669180603796127, 0.0027069009633260447, 

In [24]:
norm(d[7])

0.1

In [3]:
x1,x2 = [1,2,3],[[1,2,3],[3,4,5]]
x3,x4 = [1,2,3],[[1,2,3],[3,4,5]]

([1, 2, 3], Array{Int64,1}[[1, 2, 3], [3, 4, 5]])

In [4]:
a = []
a = push!(a, x1,x2)

2-element Array{Any,1}:
 [1, 2, 3]                           
 Array{Int64,1}[[1, 2, 3], [3, 4, 5]]

In [6]:
a = push!(a, x3,x4)

4-element Array{Any,1}:
 [1, 2, 3]                           
 Array{Int64,1}[[1, 2, 3], [3, 4, 5]]
 [1, 2, 3]                           
 Array{Int64,1}[[1, 2, 3], [3, 4, 5]]

In [9]:
a[3]

3-element Array{Int64,1}:
 1
 2
 3

In [6]:
function lorenz(x, y, z, s=10, r=28, b=2.667)
    x_dot = s*(y - x)
    y_dot = r*x - y - x*z
    z_dot = x*y - b*z
    return x_dot, y_dot, z_dot
end


dt = 0.01
num_steps = 10000

# Need one more for the initial values
xs = np.empty(num_steps + 1)
ys = np.empty(num_steps + 1)
zs = np.empty(num_steps + 1)

# Set initial values
xs[1], ys[1], zs[1] = (0.0, 1.0, 1.05)

# Step through "time", calculating the partial derivatives at the current point
# and using them to estimate the next point
for i in 1:num_steps
    x_dot, y_dot, z_dot = lorenz(xs[i], ys[i], zs[i])
    xs[i + 1] = xs[i] + (x_dot * dt)
    ys[i + 1] = ys[i] + (y_dot * dt)
    zs[i + 1] = zs[i] + (z_dot * dt)
end



1-element Array{PyObject,1}:
 PyObject <mpl_toolkits.mplot3d.art3d.Line3D object at 0x0000000000E6DD68>

In [11]:
asd = pyimport("mpl_toolkits.mplot3d")
fig = plt.figure()
ax = plt.axes(projection="3d")
ax.plot3D(xs, ys, zs, "gray", linewidth = 0.5)

ax.set_xlabel("X")
ax.set_ylabel("Y")
ax.set_zlabel("Z")

PyObject Text(0.09113564449804981, 0.01220986117247108, 'Z')

In [1]:
using DelimitedFiles
f = open("try.txt","w")

IOStream(<file try.txt>)

In [3]:
fv = open("try.txt","a")
tarray = 1:1:10
number = 10
result = 1:0.5:5.5
proba = zeros(10)
for m in 1:length(tarray)
    condition = tarray[m]
    dummy = 0
    for o in 1:number
        if result[o] >= condition
            dummy += 1
        else
            dummy = dummy
        end
    end
    dummy = dummy/number
    if dummy == 0.0
        break
    else
        proba[m] = dummy
    end
    println("done for one iteration")
end
writedlm(fv, proba)
close(fv)

done for one iteration
done for one iteration
done for one iteration
done for one iteration
done for one iteration
