In [2]:
isnan(NaN) not(!) ;
NaN == NaN

LoadError: syntax: extra token "not" after end of expression

In [3]:
a = 2;
b = 2;
a == b

true

In [4]:
a === b

true

In [5]:
a ==== b

LoadError: syntax: unexpected "="

In [6]:
b = "2";

In [7]:
a == b

false

In [8]:
a === b

false

In [11]:
chr = 'c'

'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)

In [12]:
typeof(chr)

Char

In [17]:
chr = '2'

'2': ASCII/Unicode U+0032 (category Nd: Number, decimal digit)

In [18]:
typeof(chr) 

Char

In [19]:
chr

'2': ASCII/Unicode U+0032 (category Nd: Number, decimal digit)

In [20]:
Int(chr)

50

In [21]:
Int('J')

74

In [22]:
chr = 'a'

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [23]:
Int('a')

97

In [25]:
Int('c')

99

In [26]:
Int('j')

106

In [27]:
Int('A')

65

In [29]:
chr = '\U0062'

'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)

In [30]:
chr

'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)

In [32]:
'\u0062'

'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)

In [33]:
'\u80FFFF00'

LoadError: syntax: invalid character literal

In [34]:
str = "A string"

"A string"

In [38]:
for i in str
    println(i)
end

A
 
s
t
r
i
n
g


In [39]:
chr = 'a'

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [40]:
for i in chr

LoadError: syntax: incomplete: premature end of input

In [407]:
for i in chr
    println(i)
end

a


In [44]:
str  = "learn"*" "*"Julia"

"learn Julia"

In [58]:
a = b = 2
println("$a * $b ")

2 * 2 


In [59]:
?findfirst

search: findfirst



```
findfirst(A)
```

Return the index or key of the first `true` value in `A`. Return `nothing` if no such value is found. To search for other kinds of values, pass a predicate as the first argument.

Indices or keys are of the same type as those returned by [`keys(A)`](@ref) and [`pairs(A)`](@ref).

# Examples

```jldoctest
julia> A = [false, false, true, false]
4-element Array{Bool,1}:
 0
 0
 1
 0

julia> findfirst(A)
3

julia> findfirst(falses(3)) # returns nothing, but not printed in the REPL

julia> A = [false false; true false]
2×2 Array{Bool,2}:
 0  0
 1  0

julia> findfirst(A)
CartesianIndex(2, 1)
```

---

```
findfirst(predicate::Function, A)
```

Return the index or key of the first element of `A` for which `predicate` returns `true`. Return `nothing` if there is no such element.

Indices or keys are of the same type as those returned by [`keys(A)`](@ref) and [`pairs(A)`](@ref).

# Examples

```jldoctest
julia> A = [1, 4, 2, 2]
4-element Array{Int64,1}:
 1
 4
 2
 2

julia> findfirst(iseven, A)
2

julia> findfirst(x -> x>10, A) # returns nothing, but not printed in the REPL

julia> findfirst(isequal(4), A)
2

julia> A = [1 4; 2 2]
2×2 Array{Int64,2}:
 1  4
 2  2

julia> findfirst(iseven, A)
CartesianIndex(2, 1)
```

---

```
findfirst(pattern::AbstractString, string::AbstractString)
findfirst(pattern::Regex, string::String)
```

Find the first occurrence of `pattern` in `string`. Equivalent to [`findnext(pattern, string, firstindex(s))`](@ref).

# Examples

```jldoctest
julia> findfirst("z", "Hello to the world") # returns nothing, but not printed in the REPL

julia> findfirst("Julia", "JuliaLang")
1:5
```


In [70]:
a = [1 2 5 6]
findfirst(isequal(2),a) == (1,2)

false

In [71]:
replace("Julia", "a" => "us")

"Julius"

In [72]:
replace("asjhduasdhg", "a"=>"w")

"wsjhduwsdhg"

In [73]:
lastindex("Hello") == 5

true

In [74]:
pattern = r"l[aeiou]"

r"l[aeiou]"

In [78]:
patern = r"[akdgoahrgk]"

r"[akdgoahrgk]"

In [98]:
pat = r"\+([0-9]) ([0-9]+)"

r"\+([0-9]) ([0-9]+)"

In [99]:
str = "+1 234 567 890 567"

"+1 234 567 890 567"

In [100]:
m = match(pat, str)

RegexMatch("+1 234", 1="1", 2="234")

In [85]:
lastindex("123")

3

In [86]:
length("123")

3

In [93]:
"Ångström"[9]

StringIndexError: StringIndexError("Ångström", 9)

In [89]:
length("Ångström")

8

In [101]:
T = complex{1+1i}

UndefVarError: UndefVarError: i not defined

In [102]:
T = complex(1+i)

UndefVarError: UndefVarError: i not defined

In [103]:
?complex

search: complex Complex ComplexF64 ComplexF32 ComplexF16 precompile



```
complex(r, [i])
```

Convert real numbers or arrays to complex. `i` defaults to zero.

# Examples

```jldoctest
julia> complex(7)
7 + 0im

julia> complex([1, 2, 3])
3-element Array{Complex{Int64},1}:
 1 + 0im
 2 + 0im
 3 + 0im
```

---

```
complex(T::Type)
```

Return an appropriate type which can represent a value of type `T` as a complex number. Equivalent to `typeof(complex(zero(T)))`.

# Examples

```jldoctest
julia> complex(Complex{Int})
Complex{Int64}

julia> complex(Int)
Complex{Int64}
```


In [115]:
complex([7,1])

2-element Array{Complex{Int64},1}:
 7 + 0im
 1 + 0im

In [107]:
complex([1,2])

2-element Array{Complex{Int64},1}:
 1 + 0im
 2 + 0im

In [110]:
r = typeof(complex(zero(Int64)))

Complex{Int64}

In [116]:
r = 1+2im

1 + 2im

In [117]:
?match

search: match eachmatch RegexMatch DimensionMismatch MathConstants



```
match(r::Regex, s::AbstractString[, idx::Integer[, addopts]])
```

Search for the first match of the regular expression `r` in `s` and return a `RegexMatch` object containing the match, or nothing if the match failed. The matching substring can be retrieved by accessing `m.match` and the captured sequences can be retrieved by accessing `m.captures` The optional `idx` argument specifies an index at which to start the search.

# Examples

```jldoctest
julia> rx = r"a(.)a"
r"a(.)a"

julia> m = match(rx, "cabac")
RegexMatch("aba", 1="b")

julia> m.captures
1-element Array{Union{Nothing, SubString{String}},1}:
 "b"

julia> m.match
"aba"

julia> match(rx, "cabac", 3) === nothing
true
```


In [118]:
nothing

In [119]:
a = nothing

In [120]:
a

In [121]:
rx = r"a(.)a"
m = match(rx, "cabac")

RegexMatch("aba", 1="b")

In [122]:
m.match

"aba"

In [127]:
match(rx,"cabac",4)

In [128]:
a = [1,2,3,4,5,6]

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [129]:
min(a)

MethodError: MethodError: no method matching min(::Array{Int64,1})
Closest candidates are:
  min(::Any, !Matched::Missing) at missing.jl:101
  min(::Any, !Matched::Any) at operators.jl:422
  min(::Any, !Matched::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
  ...

In [130]:
typemin(a)

MethodError: MethodError: no method matching typemin(::Array{Int64,1})
Closest candidates are:
  typemin(!Matched::Type{Bool}) at bool.jl:6
  typemin(!Matched::Type{Int8}) at int.jl:665
  typemin(!Matched::Type{UInt8}) at int.jl:667
  ...

In [131]:
?min

search: min minmax minimum minimum! argmin Main typemin findmin findmin!



```
min(x, y, ...)
```

Return the minimum of the arguments. See also the [`minimum`](@ref) function to take the minimum element from a collection.

# Examples

```jldoctest
julia> min(2, 5, 1)
1
```


In [132]:
a.add(4)

ErrorException: type Array has no field add

In [133]:
?array

search: Array SubArray BitArray DenseArray StridedArray PermutedDimsArray

Couldn't find array
Perhaps you meant Array, argmax, any, atan, read, real, rpad, break or error


No documentation found.

Binding `array` does not exist.


In [134]:
pi

π = 3.1415926535897...

In [135]:
im*im

-1 + 0im

In [136]:
real(im*im)

-1

In [137]:
complex(im*im)

-1 + 0im

In [138]:
imaginary(im*im)

UndefVarError: UndefVarError: imaginary not defined

In [139]:
?complex.real

MethodError: MethodError: no method matching Base.Docs.Binding(::typeof(complex), ::Symbol)
Closest candidates are:
  Base.Docs.Binding(!Matched::Module, ::Symbol) at docs\bindings.jl:12

In [140]:
e

UndefVarError: UndefVarError: e not defined

In [141]:
exp

exp (generic function with 13 methods)

In [142]:
?exp

search: exp exp2 Expr expm1 exp10 export exponent expanduser ExponentialBackOff



```
exp(x)
```

Compute the natural base exponential of `x`, in other words $e^x$.

# Examples

```jldoctest
julia> exp(1.0)
2.718281828459045
```

---

```
exp(A::AbstractMatrix)
```

Compute the matrix exponential of `A`, defined by

$$
e^A = \sum_{n=0}^{\infty} \frac{A^n}{n!}.
$$

For symmetric or Hermitian `A`, an eigendecomposition ([`eigen`](@ref)) is used, otherwise the scaling and squaring algorithm (see [^H05]) is chosen.

[^H05]: Nicholas J. Higham, "The squaring and scaling method for the matrix exponential revisited", SIAM Journal on Matrix Analysis and Applications, 26(4), 2005, 1179-1193. [doi:10.1137/090768539](https://doi.org/10.1137/090768539)

# Examples

```jldoctest
julia> A = Matrix(1.0I, 2, 2)
2×2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

julia> exp(A)
2×2 Array{Float64,2}:
 2.71828  0.0
 0.0      2.71828
```


In [143]:
exp(1)

2.718281828459045

In [144]:
?eps


search: eps @elapsed expanduser escape_string setprecision peakflops



```
eps(::Type{T}) where T<:AbstractFloat
eps()
```

Return the *machine epsilon* of the floating point type `T` (`T = Float64` by default). This is defined as the gap between 1 and the next largest value representable by `typeof(one(T))`, and is equivalent to `eps(one(T))`.  (Since `eps(T)` is a bound on the *relative error* of `T`, it is a "dimensionless" quantity like [`one`](@ref).)

# Examples

```jldoctest
julia> eps()
2.220446049250313e-16

julia> eps(Float32)
1.1920929f-7

julia> 1.0 + eps()
1.0000000000000002

julia> 1.0 + eps()/2
1.0
```

---

```
eps(x::AbstractFloat)
```

Return the *unit in last place* (ulp) of `x`. This is the distance between consecutive representable floating point values at `x`. In most cases, if the distance on either side of `x` is different, then the larger of the two is taken, that is

```
eps(x) == max(x-prevfloat(x), nextfloat(x)-x)
```

The exceptions to this rule are the smallest and largest finite values (e.g. `nextfloat(-Inf)` and `prevfloat(Inf)` for [`Float64`](@ref)), which round to the smaller of the values.

The rationale for this behavior is that `eps` bounds the floating point rounding error. Under the default `RoundNearest` rounding mode, if $y$ is a real number and $x$ is the nearest floating point number to $y$, then

$$
|y-x| \leq \operatorname{eps}(x)/2.
$$

# Examples

```jldoctest
julia> eps(1.0)
2.220446049250313e-16

julia> eps(prevfloat(2.0))
2.220446049250313e-16

julia> eps(2.0)
4.440892098500626e-16

julia> x = prevfloat(Inf)      # largest finite Float64
1.7976931348623157e308

julia> x + eps(x)/2            # rounds up
Inf

julia> x + prevfloat(eps(x)/2) # rounds down
1.7976931348623157e308
```

---

```
eps(::DateTime) -> Millisecond
eps(::Date) -> Day
eps(::Time) -> Nanosecond
```

Returns `Millisecond(1)` for `DateTime` values, `Day(1)` for `Date` values, and `Nanosecond(1)` for `Time` values.


In [145]:
eps()

2.220446049250313e-16

In [146]:
1+eps()

1.0000000000000002

In [147]:
eps(Float64)

2.220446049250313e-16

In [149]:
eps(Float32)

1.1920929f-7

In [150]:
eps(Float16)

Float16(0.000977)

In [153]:
?prevfloat

search: prevfloat



```
prevfloat(x::AbstractFloat, n::Integer)
```

The result of `n` iterative applications of `prevfloat` to `x` if `n >= 0`, or `-n` applications of `nextfloat` if `n < 0`.

---

```
prevfloat(x::AbstractFloat)
```

Return the largest floating point number `y` of the same type as `x` such `y < x`. If no such `y` exists (e.g. if `x` is `-Inf` or `NaN`), then return `x`.


In [156]:
prevfloat(9.000, 3)

8.999999999999995

In [161]:
MathConstants


Base.MathConstants

In [165]:
using Base.MathConstants

In [167]:
?MathConstants


search: MathConstants



```
Base.MathConstants
```

Module containing the mathematical constants. See [`π`](@ref), [`ℯ`](@ref), [`γ`](@ref), [`φ`](@ref) and [`catalan`](@ref).


In [168]:
?catalan

search: catalan AbstractIrrational



```
catalan
```

Catalan's constant.

# Examples

```jldoctest
julia> Base.MathConstants.catalan
catalan = 0.9159655941772...
```


In [171]:
using Distributions;
my_dist = Bernoulli(0.2)

ArgumentError: ArgumentError: Package Distributions not found in current path:
- Run `import Pkg; Pkg.add("Distributions")` to install the Distributions package.


In [172]:
?randsubseq

search:

Couldn't find randsubseq
Perhaps you meant transpose


No documentation found.

Binding `randsubseq` does not exist.


In [173]:
?rand

search: rand randn transcode macroexpand @macroexpand @macroexpand1



```
rand([rng=GLOBAL_RNG], [S], [dims...])
```

Pick a random element or array of random elements from the set of values specified by `S`; `S` can be

  * an indexable collection (for example `1:9` or `('x', "y", :z)`),
  * an `AbstractDict` or `AbstractSet` object,
  * a string (considered as a collection of characters), or
  * a type: the set of values to pick from is then equivalent to `typemin(S):typemax(S)` for integers (this is not applicable to [`BigInt`](@ref)), and to $[0, 1)$ for floating point numbers;

`S` defaults to [`Float64`](@ref).

!!! compat "Julia 1.1"
    Support for `S` as a tuple requires at least Julia 1.1.


# Examples

```julia-repl
julia> rand(Int, 2)
2-element Array{Int64,1}:
 1339893410598768192
 1575814717733606317

julia> using Random

julia> rand(MersenneTwister(0), Dict(1=>2, 3=>4))
1=>2
```

!!! note
    The complexity of `rand(rng, s::Union{AbstractDict,AbstractSet})` is linear in the length of `s`, unless an optimized method with constant complexity is available, which is the case for `Dict`, `Set` and `BitSet`. For more than a few calls, use `rand(rng, collect(s))` instead, or either `rand(rng, Dict(s))` or `rand(rng, Set(s))` as appropriate.



In [174]:
a = ["Julia is", 100, '%', :cool]

4-element Array{Any,1}:
    "Julia is"
 100          
    '%'       
    :cool     

In [175]:
typeof(a)

Array{Any,1}

In [176]:
arr = Float64[]

0-element Array{Float64,1}

In [177]:
arr = Int64[]

0-element Array{Int64,1}

In [178]:
sizehint!(arr, 10^4)

0-element Array{Int64,1}

In [179]:
arr = Any[1,2]

2-element Array{Any,1}:
 1
 2

In [180]:
arr[1] == "Some text"

false

In [181]:
arr[1]

1

In [182]:
Any

Any

In [183]:
?Any

search: Any any any! code_warntype ReadOnlyMemoryError @code_warntype isreadonly



```
Any::DataType
```

`Any` is the union of all types. It has the defining property `isa(x, Any) == true` for any `x`. `Any` therefore describes the entire universe of possible values. For example `Integer` is a subset of `Any` that includes `Int`, `Int8`, and other integer types.


In [223]:
using LinearAlgebra

In [185]:
Int64 == Any

false

In [227]:
a = [[1:10 1:10 1:10];[1:10 1:10 1:10]]
transpose(a)

3×20 Transpose{Int64,Array{Int64,2}}:
 1  2  3  4  5  6  7  8  9  10  1  2  3  4  5  6  7  8  9  10
 1  2  3  4  5  6  7  8  9  10  1  2  3  4  5  6  7  8  9  10
 1  2  3  4  5  6  7  8  9  10  1  2  3  4  5  6  7  8  9  10

In [212]:
arr[4:2]

0-element Array{UnitRange{Int64},1}

In [188]:
a[2]

BoundsError: BoundsError: attempt to access 1-element Array{UnitRange{Int64},1} at index [2]

In [228]:
arr

2-element Array{UnitRange{Int64},1}:
 1:10
 2:11

In [229]:
a

20×3 Array{Int64,2}:
  1   1   1
  2   2   2
  3   3   3
  4   4   4
  5   5   5
  6   6   6
  7   7   7
  8   8   8
  9   9   9
 10  10  10
  1   1   1
  2   2   2
  3   3   3
  4   4   4
  5   5   5
  6   6   6
  7   7   7
  8   8   8
  9   9   9
 10  10  10

In [230]:
a.append(1)

ErrorException: type Array has no field append

In [232]:
a[2:3]

2-element Array{Int64,1}:
 2
 3

a[2]

In [233]:
a[2]

2

In [234]:
a

20×3 Array{Int64,2}:
  1   1   1
  2   2   2
  3   3   3
  4   4   4
  5   5   5
  6   6   6
  7   7   7
  8   8   8
  9   9   9
 10  10  10
  1   1   1
  2   2   2
  3   3   3
  4   4   4
  5   5   5
  6   6   6
  7   7   7
  8   8   8
  9   9   9
 10  10  10

In [235]:
a = [2 4 6 61 1 4 5]

1×7 Array{Int64,2}:
 2  4  6  61  1  4  5

In [236]:
a[2:5]

4-element Array{Int64,1}:
  4
  6
 61
  1

In [237]:
ones(9)

9-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [240]:
Vector{Float64}(undef,3)

3-element Array{Float64,1}:
 1.50040456e-315 
 1.500122667e-315
 1.50040472e-315 

In [241]:
?undef

search: undef UndefVarError UndefRefError UndefInitializer UndefKeywordError



```
undef
```

Alias for `UndefInitializer()`, which constructs an instance of the singleton type [`UndefInitializer`](@ref), used in array initialization to indicate the array-constructor-caller would like an uninitialized array.

# Examples

```julia-repl
julia> Array{Float64,1}(undef, 3)
3-element Array{Float64,1}:
 2.2752528595e-314
 2.202942107e-314
 2.275252907e-314
```


In [273]:
a = Float64[]
for i in 1.0:2:9.0
    println(i)
    append!(a,i)
end
return a

1.0
3.0
5.0
7.0
9.0


5-element Array{Float64,1}:
 1.0
 3.0
 5.0
 7.0
 9.0

In [346]:
a = [1, 1,1]; 
A = fill!(Vector{Vector{Float64}}(undef, 3), a); 
a[1] = 4.0; 
A

3-element Array{Array{Float64,1},1}:
 [1.0, 1.0, 1.0]
 [1.0, 1.0, 1.0]
 [1.0, 1.0, 1.0]

In [295]:
in([1.0,1.0,1.0],A),
A[1]

(true, [1.0, 1.0, 1.0])

In [296]:
a

3-element Array{Int64,1}:
 4
 1
 1

In [305]:
a*transpose(a)

3×3 Array{Int64,2}:
 16  4  4
  4  1  1
  4  1  1

In [306]:
dot(a,a)

18

In [312]:
?sum

search: sum sum! summary cumsum cumsum! isnumeric VersionNumber issubnormal



```
sum(f, itr)
```

Sum the results of calling function `f` on each element of `itr`.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

# Examples

```jldoctest
julia> sum(abs2, [2; 3; 4])
29
```

Note the important difference between `sum(A)` and `reduce(+, A)` for arrays with small integer eltype:

```jldoctest
julia> sum(Int8[100, 28])
128

julia> reduce(+, Int8[100, 28])
-128
```

In the former case, the integers are widened to system word size and therefore the result is 128. In the latter case, no such widening happens and integer overflow results in -128.

---

```
sum(itr)
```

Returns the sum of all elements in a collection.

The return type is `Int` for signed integers of less than system word size, and `UInt` for unsigned integers of less than system word size.  For all other arguments, a common return type is found to which all arguments are promoted.

# Examples

```jldoctest
julia> sum(1:20)
210
```

---

```
sum(A::AbstractArray; dims)
```

Sum elements of an array over the given dimensions.

# Examples

```jldoctest
julia> A = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> sum(A, dims=1)
1×2 Array{Int64,2}:
 4  6

julia> sum(A, dims=2)
2×1 Array{Int64,2}:
 3
 7
```


In [316]:
b = [2;3;4]

3-element Array{Int64,1}:
 2
 3
 4

In [323]:
abs2

abs2 (generic function with 4 methods)

In [324]:
sum(abs2,a)

18

In [325]:
sqrt

sqrt (generic function with 19 methods)

In [330]:
 reduce(-, Int8[100, 28])

72

In [329]:
 reduce(*, Int8[100, 28])

-16

In [331]:
?reduce

search: reduce mapreduce



```
reduce(op, itr; [init])
```

Reduce the given collection `itr` with the given binary operator `op`. If provided, the initial value `init` must be a neutral element for `op` that will be returned for empty collections. It is unspecified whether `init` is used for non-empty collections.

For empty collections, providing `init` will be necessary, except for some special cases (e.g. when `op` is one of `+`, `*`, `max`, `min`, `&`, `|`) when Julia can determine the neutral element of `op`.

Reductions for certain commonly-used operators may have special implementations, and should be used instead: `maximum(itr)`, `minimum(itr)`, `sum(itr)`, `prod(itr)`,  `any(itr)`, `all(itr)`.

The associativity of the reduction is implementation dependent. This means that you can't use non-associative operations like `-` because it is undefined whether `reduce(-,[1,2,3])` should be evaluated as `(1-2)-3` or `1-(2-3)`. Use [`foldl`](@ref) or [`foldr`](@ref) instead for guaranteed left or right associativity.

Some operations accumulate error. Parallelism will be easier if the reduction can be executed in groups. Future versions of Julia might change the algorithm. Note that the elements are not reordered if you use an ordered collection.

# Examples

```jldoctest
julia> reduce(*, [2; 3; 4])
24

julia> reduce(*, [2; 3; 4]; init=-1)
-24
```

---

```
reduce(f, A; dims=:, [init])
```

Reduce 2-argument function `f` along dimensions of `A`. `dims` is a vector specifying the dimensions to reduce, and the keyword argument `init` is the initial value to use in the reductions. For `+`, `*`, `max` and `min` the `init` argument is optional.

The associativity of the reduction is implementation-dependent; if you need a particular associativity, e.g. left-to-right, you should write your own loop or consider using [`foldl`](@ref) or [`foldr`](@ref). See documentation for [`reduce`](@ref).

# Examples

```jldoctest
julia> a = reshape(Vector(1:16), (4,4))
4×4 Array{Int64,2}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

julia> reduce(max, a, dims=2)
4×1 Array{Int64,2}:
 13
 14
 15
 16

julia> reduce(max, a, dims=1)
1×4 Array{Int64,2}:
 4  8  12  16
```


In [345]:
a

5×2 Array{Int64,2}:
 1  2
 3  4
 5  5
 7  9
 1  2

In [333]:
reshape(a,1,3)

1×3 Array{Int64,2}:
 4  1  1

In [334]:
max(a)

MethodError: MethodError: no method matching max(::Array{Int64,1})
Closest candidates are:
  max(::Any, !Matched::Missing) at missing.jl:104
  max(::Any, !Matched::Any) at operators.jl:408
  max(::Any, !Matched::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
  ...

In [335]:
max[a]

MethodError: MethodError: no method matching getindex(::typeof(max), ::Array{Int64,1})

In [336]:
max(1,2,3)

3

In [337]:
max([1,2,3])

MethodError: MethodError: no method matching max(::Array{Int64,1})
Closest candidates are:
  max(::Any, !Matched::Missing) at missing.jl:104
  max(::Any, !Matched::Any) at operators.jl:408
  max(::Any, !Matched::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
  ...

In [338]:
max([1; 2; 3])

MethodError: MethodError: no method matching max(::Array{Int64,1})
Closest candidates are:
  max(::Any, !Matched::Missing) at missing.jl:104
  max(::Any, !Matched::Any) at operators.jl:408
  max(::Any, !Matched::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
  ...

In [342]:
a=[1 2; 3 4; 5 5; 7 9; 1 2]

5×2 Array{Int64,2}:
 1  2
 3  4
 5  5
 7  9
 1  2

In [348]:
x,y = findmax(a)

(4, 1)

In [350]:
x = []

0-element Array{Any,1}

In [437]:
function Matching_Points_Arrays(Input_Array,Data, f)
    Output_Array = []
    for x in Input_Array
        Up = searchsortedfirst(Data, x)
        if x == Data[Up]
            append!(Output_Array,f(x))
        else
            Low = Up - 1
            Value = f(Data[Low]) + ((x - Data[Low])/(Data[Up] - Data[Low]))*(f(Data[Up])-f(Data[Low]))
            append!(Output_Array, Value)
        end
    end
    return Output_Array
end

Matching_Points_Arrays (generic function with 1 method)

In [438]:
function g(x)
    return 2*x
end

g (generic function with 1 method)

In [439]:
g(2)

4

In [441]:
Matching_Points_Arrays([2,3.5,4,5.3,5.8,6,6.8,7],[2,3,4,5,6,7],g)

8-element Array{Any,1}:
  4.0
  7.0
  8.0
 10.6
 11.6
 12.0
 13.6
 14.0

In [410]:
for i in [1,2,3]
    println(i)
end

1
2
3


In [369]:
a = []

0-element Array{Any,1}

In [370]:
append!(a,1)

1-element Array{Any,1}:
 1

In [371]:
append!(a,2)

2-element Array{Any,1}:
 1
 2

In [1]:
z = error("Out of Order")

ErrorException: Out of Order

In [42]:
function OrderedPair(x,y)
    return x + y
end

OrderedPair

In [48]:
struct OrderedPair
    x = 1
    y = 1
end

ErrorException: syntax: "x = 1" inside type definition is reserved

In [44]:
OrderedPair(2,1)

ErrorException: out of order

In [45]:
OrderedPair(1,2)

OrderedPair(2, 3)

In [6]:
?new

search: nextpow unsafe_wrap unsafe_write UndefKeywordError RoundNearestTiesAway



```
new
```

Special function available to inner constructors which created a new object of the type. See the manual section on [Inner Constructor Methods](@ref) for more information.


In [7]:
function func(x)
    x + 2
end

func (generic function with 1 method)

In [26]:
struct L1    
    x::Real
    L1(x) = new(func(x))
end

In [27]:
L1(2)

L1(4)

In [28]:
L1(5)

L1(7)

In [29]:
func(2)

4

In [18]:
L1(1+2im)

MethodError: MethodError: no method matching L1(::Complex{Int64})
Closest candidates are:
  L1(!Matched::Real) at In[14]:3

In [10]:
ts = 0:1:500;
ηs = cos.(ts);
ηs

501-element Array{Float64,1}:
  1.0                 
  0.5403023058681398  
 -0.4161468365471424  
 -0.9899924966004454  
 -0.6536436208636119  
  0.28366218546322625 
  0.960170286650366   
  0.7539022543433046  
 -0.14550003380861354 
 -0.9111302618846769  
 -0.8390715290764524  
  0.004425697988050785
  0.8438539587324921  
  ⋮                   
  0.46385557427185253 
  0.9960904985055212  
  0.6125244121199033  
 -0.3341937939677003  
 -0.9736557670950443  
 -0.7179431181988293  
  0.19784312260506456 
  0.9317333088861682  
  0.8089921878856322  
 -0.05753261979833144 
 -0.8711622021649791  
 -0.883849273431478   

In [16]:
a = [1;2;3]
b = 2 .+(a)

3-element Array{Int64,1}:
 3
 4
 5

In [30]:
interval_range = 0:0.5:12
input = [0.5,0.5,1.0,0.5,2.3,4.6]
output = zeros(length(interval_range)-1)

for i in input
    for j in 1:(length(interval_range)-1)
        if i <= interval_range[j+1] && i> interval_range[j]
            output[j] += 1
        else
            output = output
        end
    end
end

dummy = 1
for i in 1:length(output)
    value = output[i]
    start! = interval_range[dummy]
    END! = interval_range[dummy+1]
    println("$value numbers in the range of $start! to $END!")
    dummy += 1
end

3.0 numbers in the range of 0.0 to 0.5
1.0 numbers in the range of 0.5 to 1.0
0.0 numbers in the range of 1.0 to 1.5
0.0 numbers in the range of 1.5 to 2.0
1.0 numbers in the range of 2.0 to 2.5
0.0 numbers in the range of 2.5 to 3.0
0.0 numbers in the range of 3.0 to 3.5
0.0 numbers in the range of 3.5 to 4.0
0.0 numbers in the range of 4.0 to 4.5
1.0 numbers in the range of 4.5 to 5.0
0.0 numbers in the range of 5.0 to 5.5
0.0 numbers in the range of 5.5 to 6.0
0.0 numbers in the range of 6.0 to 6.5
0.0 numbers in the range of 6.5 to 7.0
0.0 numbers in the range of 7.0 to 7.5
0.0 numbers in the range of 7.5 to 8.0
0.0 numbers in the range of 8.0 to 8.5
0.0 numbers in the range of 8.5 to 9.0
0.0 numbers in the range of 9.0 to 9.5
0.0 numbers in the range of 9.5 to 10.0
0.0 numbers in the range of 10.0 to 10.5
0.0 numbers in the range of 10.5 to 11.0
0.0 numbers in the range of 11.0 to 11.5
0.0 numbers in the range of 11.5 to 12.0


In [29]:
length(interval_range)

25

In [21]:
length(0:0.5:1.5)

4

In [25]:
output

25-element Array{Float64,1}:
 3.0
 1.0
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [16]:
2 .+ [1,2] 

2-element Array{Int64,1}:
 3
 4