In [1]:
using Flows
using ToySystems
using ToySystems.NineModeSystemEq
using Optim
using PyPlot; pygui(true)
include("9msctrl.jl")
using PyCall
include("Magnitude Rand.jl")
include("Objective function Monitor.jl")
include("AdjointControl.jl")
plt = pyimport("matplotlib.pyplot");

┌ Info: Recompiling stale cache file C:\Users\User\.julia\compiled\v1.2\ToySystems\chsON.ji for ToySystems [53c88820-6eff-5a8c-9a74-badd815e7be1]
└ @ Base loading.jl:1240
┌ Warning: Package ToySystems does not have Flows in its dependencies:
│ - If you have ToySystems checked out for development and have
│   added Flows as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with ToySystems
└ Loading Flows into ToySystems from project dependency, future warnings for ToySystems are suppressed.


In [8]:
# function Continuous_CTRL_Objfun(Reynolds,Initial_Time, Final_Time,uinitial,n,αv)
#     u0 = uinitial
#     Re = Reynolds
#     Tf = Final_Time
#     T = Tf/n
#     Tfn = T
#     Ti = Initial_Time
#     ts = Ti:timestep:Tfn
#     output_CTRL = zeros(1)
#     α = αv
    
#     for i in 1:n
        
        
        
#         function Objective_fun_CTRL(η::AbstractVector) ##Take note on Re, T, and u0
#             f = NineModeSystemCTRL(Re, ts, η)
#             ϕ = flow(couple(f,objfun),RK4(couple(zeros(9),zeros(1))), TimeStepConstant(timestep))
#             I0 = Float64[0.0]
#             u0_local = copy(u0)
#             ϕ(couple(u0_local, I0), extrema(ts))
#             return I0[1]/T + α.*η2int(η, timestep) ## T is a constant
#         end
#         function Objective_fun_Gradient!(G::AbstractVector,η::AbstractVector)
#             f = NineModeSystemCTRL(Re, ts, η)
#             ϕ = flow(f,RK4(zeros(9)), TimeStepConstant(timestep))
#             u0_local = copy(u0)
#             ϕ(u0_local, (Ti, Tfn), reset!(store))

#             h = NineModeSystemLin(Re, true, minus_energy_grad)
#             ψ_adj = flow(h, RK4(zeros(9), ContinuousMode(true)), TimeStepFromStorage(timestep))
#             mon = Monitor(zeros(9), q -> -B[5]*q[5])
#             ψ_adj(zeros(9), store, (Tfn, Ti), reset!(mon))
#             G .= samples(mon)[end:-1:1] .+ 2.0.*α.*η
#         end
#         function finalpoint(η)
#             u0_local = copy(u0)
#             f = NineModeSystemCTRL(Re, ts, η)
#             F = flow(f, RK4(zeros(9)), TimeStepConstant(timestep))
#             return F(u0_local, extrema(ts))
#             end #functions which will be reiterated
        
        
        
        
#         result = optimize(Objective_fun_CTRL, Objective_fun_Gradient!, zeros(length(ts)),LBFGS(),Optim.Options(f_tol = 1e-6,
#                              store_trace = false,
#                              show_trace = false))
#         η = result.minimizer
#         output_CTRL = vcat(output_CTRL, result.minimizer)
#         u0 = finalpoint(η)
        
#         Ti = Tfn + timestep
#         Tfn = Tfn + T
#         ts = Ti:timestep: Tfn
#     end
#     return output_CTRL[2:end]
# end

minus_energy_grad (generic function with 1 method)

In [3]:
# u0 = rand(9)

In [4]:
# Tfg = 1000
# Reg = 400
# timestep = 0.5
# tsg = 0:0.5:1000
# α_range = 0.1:0.1:0.5
# n = 5

# x_array = ts = tsg
# y_array = zeros(length(ts), length(α_range))


# for i in 1:length(α_range)
#     α = α_range[i]
#     final = Continuous_CTRL_Objfun(Reg, 0,Tfg, u0, n, α)
# #     final2 = Continuous_CTRL_Objfun(Reg, Tfg, u0, 1, α)
    
#     ff = NineModeSystemCTRL(Reg, tsg, final)
#     F = flow(couple(ff, objfun), RK4(couple(zeros(9), zeros(1))), TimeStepConstant(timestep))
#     I0 = Float64[0.0]
#     u0_local = copy(u0)
#     mon = Monitor(couple(zeros(9), zeros(1)), objfun)
#     F(couple(u0_local,I0), extrema(ts), reset!(mon))
#     y_array[:,i] = samples(mon)
    
# #     ff = NineModeSystemCTRL(Reg, tsg, final2)
# #     F = flow(couple(ff, objfun), RK4(couple(zeros(9), zeros(1))), TimeStepConstant(timestep))
# #     I0 = Float64[0.0]
# #     u0_local = copy(u0)
# #     mon = Monitor(couple(zeros(9), zeros(1)), objfun)
# #     F(couple(u0_local,I0), extrema(ts), reset!(mon))
# #     y_array[length(ts)+1:end, i] = samples(mon)
# end

# fig,ax = plt.subplots()
# for i in 1:length(α_range)
#     z = α_range[i]
#     ax.plot(x_array,y_array[:,i], label = "α_$z split_$n")
# end
# ax.legend()
# # ax.plot(x_array,y_array[:,1], label = "α_0.1")
# # ax.plot(x_array,y_array[:,2], label = "α_0.2")
# # ax.plot(x_array,y_array[:,3], label = "α_0.3")
# # ax.plot(x_array,y_array[:,4], label = "α_0.4")
# # ax.plot(x_array,y_array[:,5], label = "α_0.5")
# # ax.legend()

PyObject <matplotlib.legend.Legend object at 0x00000000167AC668>

In [148]:
# n = 25
# timestep = 0.5
# T1 = 200
# Reynold_Number = 300;

In [149]:
# Ini_rand = []

# for i in 1:n
#     Ini_rand = push!(Ini_rand, mgscale(rand(9),0.3) + [1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]) # Radius = 0.3
# end

# f = NineModeSystem(Reynold_Number)
# ϕ = flow(couple(f, objfun), RK4(couple(zeros(9), zeros(1))), TimeStepConstant(timestep))
# Uncontrolled_State = []
# x = []
# Second_Point = []

# for i in 1:length(Ini_rand)
#     I0 = Float64[0.0]
#     u0_local = copy(Ini_rand[i])
#     mon = Monitor(couple(zeros(9), zeros(1)), objfun)
#     a,b = ϕ(couple(u0_local, I0), (0, T1), reset!(mon))
#     Uncontrolled_State = push!(Uncontrolled_State, samples(mon))
#     x = times(mon)
#     Second_Point = push!(Second_Point, a)
# end

# # fig,ax = plt.subplots()
# # ran = 1
# # for i in 1:length(Ini_rand)    
# #     ax.plot(x,Uncontrolled_State[i],color="grey", linestyle="dashed",label = "$ran",linewidth = 0.1)
# #     ran += 1
# # end
# α = 0.2
# m = 5
# T2 = T1+1000
# ts = T1+timestep:timestep:T2
# x2_controlled = 0

# for i in 1:length(Second_Point)
#     u0 = copy(Second_Point[i])
#     final = Continuous_CTRL_Objfun(Reynold_Number, T1+timestep, T2, u0, m, α)
#     ff = NineModeSystemCTRL(Reynold_Number, ts, final)
#     F = flow(couple(ff, objfun), RK4(couple(zeros(9), zeros(1))), TimeStepConstant(timestep))
#     I0 = Float64[0.0]
#     u0_local = copy(u0)
#     mon = Monitor(couple(zeros(9), zeros(1)), objfun)
#     F(couple(u0_local,I0), extrema(ts), reset!(mon))
#     Uncontrolled_State[i] = vcat(Uncontrolled_State[i],samples(mon))
#     x2_controlled = times(mon)
# end
# x = vcat(x,x2_controlled)

# fig,ax = plt.subplots()
# for i in 1:length(Ini_rand)    
#     ax.plot(x,Uncontrolled_State[i],color="grey", linestyle="dashed",linewidth = 0.1)
#     ran += 1
# end

# Main_line = (1/n).*sum(Uncontrolled_State)
# ax.plot(x,Main_line,color="black",linewidth = 0.5,label = "α = $α")
# ax.legend()

PyObject <matplotlib.legend.Legend object at 0x000000003E5FAB00>

In [155]:
# x[400:420]

21-element Array{Float64,1}:
 199.5
 200.0
 200.5
 201.0
 201.5
 202.0
 202.5
 203.0
 203.5
 204.0
 204.5
 205.0
 205.5
 206.0
 206.5
 207.0
 207.5
 208.0
 208.5
 209.0
 209.5

In [25]:
# n = 25
# timestep = 0.5
# T1 = 200
# Reynold_Number = 300;

# Ini_rand = []

# for i in 1:n
#     Ini_rand = push!(Ini_rand, mgscale(rand(9),0.3) + [1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]) # Radius = 0.3
# end

# f = NineModeSystem(Reynold_Number)
# ϕ = flow(couple(f, objfun), RK4(couple(zeros(9), zeros(1))), TimeStepConstant(timestep))
# Uncontrolled_State = []
# x = []
# Second_Point = []

# for i in 1:length(Ini_rand)
#     I0 = Float64[0.0]
#     u0_local = copy(Ini_rand[i])
#     mon = Monitor(couple(zeros(9), zeros(1)), objfun)
#     a,b = ϕ(couple(u0_local, I0), (0, T1), reset!(mon))
#     Uncontrolled_State = push!(Uncontrolled_State, samples(mon))
#     x = times(mon)
#     Second_Point = push!(Second_Point, a)
# end

In [2]:
store = RAMStorage(zeros(9))
B = [0,0,0,0,1,0,0,0,0]
function Continuous_CTRL_Objfun_V2(Reynolds,Initial_Time, Final_Time,timestep, uinitial,n,αv)
    u0 = uinitial
    Re = Reynolds
    Tf = Final_Time
    Ti = Initial_Time
    T = (Tf-Ti)/n
    Tfn = Ti + T
    ts = Ti:timestep:Tfn
    output_samples = zeros(1)
    α = αv
    
    for i in 1:n
        function finalpoint(η)
            u0_local = copy(u0)
            f = NineModeSystemCTRL(Re, ts, η)
            F = flow(f, RK4(zeros(9)), TimeStepConstant(timestep))
            mon1 = Monitor(zeros(9), objfun)
            ϕ = F(u0_local, extrema(ts),reset!(mon1))
            return ϕ,samples(mon1)
        end
        
        η = AdjointControl(u0, Re, Ti, timestep, Tfn, α)
        output_samples = output_samples[1:end-1]
        output_samples = vcat(output_samples, finalpoint(η)[2])
        u0 = finalpoint(η)[1]
        
        Ti = Tfn
        Tfn = Tfn + T
        ts = Ti:timestep: Tfn
    end
    return output_samples
end



function CTRL_split_graph(Re, α_range, Tiu, Tfu, Tfc, timesplit, timestep, initial_n, scale, d = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0])
    Ini_rand = []
    for i in 1:initial_n
        Ini_rand = push!(Ini_rand, mgscale(rand(9), scale) + d)
    end
    
    f = NineModeSystem(Re)
    ϕ = flow(couple(f, objfun), RK4(couple(zeros(9), zeros(1))), TimeStepConstant(timestep))
    x1 = Tiu:timestep:Tfu
    x2 = Tfu:timestep:Tfc
    Uncontrolled_State = []
    Second_Point = []

    for i in 1:length(Ini_rand)
        I0 = Float64[0.0]
        u0_local = copy(Ini_rand[i])
        mon = Monitor(couple(zeros(9), zeros(1)), objfun)
        a,b = ϕ(couple(u0_local, I0), (Tiu, Tfu), reset!(mon))
        Uncontrolled_State = push!(Uncontrolled_State, samples(mon))
        Second_Point = push!(Second_Point, a)
    end
    
    ne = (Tfc - Tfu)/timesplit
    Controlled_State_1 = []
    for i in 1:length(α_range)
        α = α_range[i]
        Controlled_State_2 = []
        for j in 1:length(Second_Point)
            uinitial = Second_Point[j]
            input123 = Continuous_CTRL_Objfun_V2(Re,Tfu, Tfc, timestep, uinitial, ne, α)
            Controlled_State_2 = push!(Controlled_State_2, input123)
        end
        Sum_Controlled = sum(Controlled_State_2)./length(Controlled_State_2)
        Controlled_State_1 = push!(Controlled_State_1, Sum_Controlled)
    end
    
    fig,ax = plt.subplots()
    for i in 1:length(Uncontrolled_State)    
        ax.plot(x1,Uncontrolled_State[i],color="grey", linestyle="dashed",linewidth = 0.1)
    end
    ax.plot(x1, sum(Uncontrolled_State)./initial_n, color = "black", linewidth = 0.5)
    
    for i in 1:length(Controlled_State_1)
        α_value = α_range[i]
        ax.plot(x2, Controlled_State_1[i], label = "α = $α_value @ Re = $Re")
    end
    ax.legend()
    
    return x1, Uncontrolled_State, x2, Controlled_State_1
end

CTRL_split_graph (generic function with 2 methods)

In [4]:
α_range = 4.0:4.0:40.0
# function CTRL_split_graph(Re, α_range, Tiu, Tfu, Tfc, timesplit, timestep, initial_n, scale, d = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0])
out1,out2,out3,out4 = CTRL_split_graph(450, α_range, 0, 200, 1200, 20, 0.5, 100, 0.3, [1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]);

3-element Array{Float64,1}:
   10.0
  100.0
 1000.0

In [25]:
out4[3]

2001-element Array{Float64,1}:
 0.7630953370059997
 0.7624789421144953
 0.7617557236928277
 0.7609282605283219
 0.7600007310365048
 0.7589788194371418
 0.7578695913945659
 0.756681344525452 
 0.755423439162835 
 0.7541061145185088
 0.752740294984091 
 0.7513373908259473
 0.7499090970229306
 ⋮                 
 0.6263759682502972
 0.6251742320506752
 0.6239893470292298
 0.6228240848616651
 0.6216798902948873
 0.6205571803816813
 0.6194556111140208
 0.618374300455339 
 0.6173120038770985
 0.6162672434235547
 0.6152383945165414
 0.6142237366188327

In [3]:
# Continuous_CTRL_Objfun_V2(300,200, 1200,0.5, rand(9),5,0.4)

4-element Array{Any,1}:
 1      
 2      
 3      
  4:4:20